[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
remappings = [
  "@chainlink/=lib/chainlink-brownie-contracts/",
  "@openzeppelin/=lib/openzeppelin-contracts/contracts/token/",
  "forge-std/=lib/forge-std/src/",
  "@aave-v3-core/=lib/aave-v3-core/contracts/",
]





